### ISSUE TITLE
add git hook

### ISSUE THREAD

**Issue by samdbeckham** [frontendne/frontendne.co.uk#11]
Add a hit hook that runs when something has been pushed to master. I keep forgetting to publish the site :(

**Comment by tempertemper** [comment]
Good idea! Merge away, sir :)

**Comment by samdbeckham** [comment]
I got something set up on a digi ocean box , but couldn't get Jekyll to run. @htmlandbacon got something going with node that ran jekyll but couldn't run git. Hopefully we can smash the two together somehow.

**Comment by samdbeckham** [comment]
This properly working now @htmlandbacon? Should we close this?

**Comment by htmlandbacon** [comment]
I haven't pushed this yet - as it will require testing.

I'll update this when I do!

**Comment by samdbeckham** [comment]
Okie doke, cheers Colin.
