### ISSUE TITLE
typo in speakers page title?

### ISSUE THREAD

**Issue by joseph-norman** [frontendne/frontendne.co.uk#29]
Hey guys,

I wasn't 100% sure where to report this... but looking at the title on the speakers page it says 'awesom'. If you point me in the right direction I'll gladly submit a PR :)

Joe

**Comment by tempertemper** [comment]
Hi Joe, the content's all database driven. I can't find the typo though… I think I'm still waking up :P

**Comment by joseph-norman** [comment]
Ah fair enough; here's where I'm seeing it:

![screen shot 2016-03-09 at 09 19 44](https://cloud.githubusercontent.com/assets/3330161/13630610/1db57eea-e5d8-11e5-84d6-89cfddad2e27.png)

Although I'm having difficult replicating it again...

**Comment by tempertemper** [comment]
Gotcha! Amended it now. Thanks Joe :)

**Comment by joseph-norman** [comment]
No worries - just thought I'd be pedantic and point it out! I'll close this now :)

**Comment by tempertemper** [comment]
haha pedantic is good! Glad you've got our backs :)
