### ISSUE TITLE
conference website on github?

### ISSUE THREAD

**Issue by ColinEberhardt** [frontendne/frontendne.co.uk#30]
Hi, just spotted a typo while submitting a talk - is the conference website on github?

**Comment by htmlandbacon** [comment]
Sadly not, it would ruin some surprises!

Do you want to drop us a DM on twitter, or email us at hi@frontendne.co.uk!

Cheers

**Comment by ColinEberhardt** [comment]
Ohhh ... I like surprises! :bangbang: 

Just a few very minor typos ... 
https://2018.frontendne.co.uk/ - s/suprises/surprises (ironic!)
https://2018.frontendne.co.uk/call-for-speakers.html - s/aound/around
https://2018.frontendne.co.uk/tickets.html  - s/suprises/surprises

good luck with everything.

**Comment by htmlandbacon** [comment]
This is why we are developers and not content-ers!

Thanks for flagging this. 🎄
