### ISSUE TITLE
Better MailChimp submissions

### ISSUE THREAD

**Issue by samdbeckham** [frontendne/frontendne.co.uk#5]
MailChimp is great, but their sign-up process is a bit fugly. Inline signups would be sooo much better.

Inlining it with AJAX would be awesome.
http://pocketproduct.com/2014/a-better-mailchimp-signup/

**Comment by tempertemper** [comment]
Looks like a nice streamlined solution.

**Comment by samdbeckham** [comment]
This is where I should probably point you to the [inline-signup](https://github.com/frontendne/frontendne.co.uk/tree/inline-signup) branch. It's not ready for a PR just yet, but it's getting there.

**Comment by samdbeckham** [comment]
Added and merged
