### ISSUE TITLE
Compiled site permissions

### ISSUE THREAD

**Issue by tempertemper** [frontendne/frontendne.co.uk#6]
Can we ignore the complied site and just compile it locally with jekyll? Or compile it before push? I'm having bother pulling the dev branch down because of the sudo permissions on the compiled site.

**Comment by samdbeckham** [comment]
Yeah, probably the best way. I'll remove it from the repo and pop it in the gitignore.

2 mins, I'll do that now

**Comment by tempertemper** [comment]
ta luv x

**Comment by samdbeckham** [comment]
Cocked up my commit message. Closing it manually
